import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Anton, Oswald } from "next/font/google";
import Wrapper from "@/components/Wrapper";
import { ClerkProvider } from "@clerk/nextjs";

// Load fonts
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "400", "700"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Racip",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&family=Aguafina+Script&family=Anton&family=Rubik+Distressed&family=Oswald:wght@200..700&family=Playwrite+CA:wght@100..400&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet"/>
          <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
        </head>
        <body>
            <Wrapper>{children}</Wrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
